import turtle
#-----------------------------------ادمک اول---------------------------------
turtle.color('green')
turtle.penup()
turtle.forward(-500)
turtle.pendown()
turtle.circle(50)
turtle.left(-90)
turtle.forward(150)
turtle.left(315)
turtle.forward(50)
turtle.forward(-50)
turtle.left(90)
turtle.forward(50)
turtle.forward(-50)
turtle.left(135)
turtle.forward(100)
turtle.left(135)
turtle.forward(50)
turtle.forward(-50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.forward(150)
turtle.pendown()
turtle.left(-135)
turtle.forward(300)
#-----------------------------فاصله بین دو ادمک------------------------------------
turtle.penup()
turtle.left(-90)
turtle.forward(550)
turtle.left(-90)
turtle.forward(1000)
#-----------------------------------ادمک دوم---------------------------------------------------
turtle.color('black')
turtle.pendown()
turtle.circle(50)
turtle.left(-90)
turtle.forward(150)
turtle.left(315)
turtle.forward(50)
turtle.forward(-50)
turtle.left(90)
turtle.forward(50)
turtle.forward(-50)
turtle.left(135)
turtle.forward(100)
turtle.left(135)
turtle.forward(50)
turtle.forward(-50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.forward(150)
turtle.pendown()
turtle.left(-135)
turtle.forward(300)
#---------------------------------------------------------خط نشانه-------------------------------------------------------
turtle.penup()
turtle.left(-90)
turtle.forward(100)
turtle.left(-90)
turtle.forward(50)
turtle.pendown()

turtle.left(210)
turtle.forward(600)

turtle.done()